-- AlterTable
ALTER TABLE `Accountant` MODIFY `role` ENUM('ADMIN', 'ACCOUNTANT', 'SHAREHOLDER') NOT NULL;

-- AlterTable
ALTER TABLE `Admin` MODIFY `role` ENUM('ADMIN', 'ACCOUNTANT', 'SHAREHOLDER') NOT NULL;

-- AlterTable
ALTER TABLE `Shareholder` MODIFY `role` ENUM('ADMIN', 'ACCOUNTANT', 'SHAREHOLDER') NOT NULL;
